name: Bump Tags on Main

on:
  push:
    branches:
      - main

jobs:
  bump-tags:
    runs-on: blacksmith
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update v4.1, v5, v5.0.1, v5.0.3, and v5.0.4 tags
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag -fa v4.1 -m "Update v4.1 tag to latest commit on main"
          git tag -fa v5 -m "Update v5 tag to latest commit on main"
          git tag -fa v5.0.1 -m "Update v5.0.1 tag to latest commit on main"
          git tag -fa v5.0.3 -m "Update v5.0.3 tag to latest commit on main"
          git tag -fa v5.0.4 -m "Update v5.0.4 tag to latest commit on main"
          git push origin v4.1 v5 v5.0.1 v5.0.3 v5.0.4 --force

      - name: Send Slack notification on success
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Updated setup-node v4.1, v5, v5.0.1, v5.0.3, and v5.0.4 tags to the latest commit on main"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CACHE_SLACK_WEBHOOK_URL }}
